POST http://localhost:4321/api/v1/users/sign-up
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "email": "test@gmail.com",
  "password": "qwerty123"
}

###

POST http://localhost:4321/api/v1/users/sign-in
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "qwerty123"
}

###

POST http://localhost:4321/api/v1/wallet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcyNjA4NzEsInN1YiI6Ik9iamVjdElEKFwiNjNmMjg3ZjRlYzdkMjc3N2RiYzE3YjRhXCIpIn0.jsKejCCRhRHCW6SMlBTF6pfIJNZkALjx6S74aD0_cgc

{
  "name": "cash",
  "userId": "63f287f4ec7d2777dbc17b4a",
  "sum": "0"
}

###

POST http://localhost:4321/api/v1/wallet/operation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcyNjA4NzEsInN1YiI6Ik9iamVjdElEKFwiNjNmMjg3ZjRlYzdkMjc3N2RiYzE3YjRhXCIpIn0.jsKejCCRhRHCW6SMlBTF6pfIJNZkALjx6S74aD0_cgc

{
  "walletId": "63f8dd0b7970cbe2303344fe",
  "income": true,
  "description": "some test operation #2",
  "sum": "100"
}


