POST http://localhost:4321/api/v1/users/sign-up
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "email": "test@gmail.com",
  "password": "qwerty123"
}

###

POST http://localhost:4321/api/v1/users/sign-in
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "qwerty123"
}

###

POST http://localhost:4321/api/v1/wallet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzczMzE1MDUsInN1YiI6Ik9iamVjdElEKFwiNjNmMjg3ZjRlYzdkMjc3N2RiYzE3YjRhXCIpIn0.YOb58XlYWZPaxrbOUfkkvCfkd4NSfL_B9dJuAZWD2P0

{
  "name": "crypto",
  "userId": "63f287f4ec7d2777dbc17b4a",
  "sum": "50"
}

###

GET http://localhost:4321/api/v1/wallet/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzc0MTk1MDgsInN1YiI6IjYzZjI4N2Y0ZWM3ZDI3NzdkYmMxN2I0YSJ9.VlsVJ5wuw_Y1_jXH2xu_KpTdx9GfRTyJe15V_oomlFU

###

GET http://localhost:4321/api/v1/wallet?walletId=63f8dd0b7970cbe2303344fe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzc1MjMyNzAsInN1YiI6IjYzZjI4N2Y0ZWM3ZDI3NzdkYmMxN2I0YSJ9._3O8yn_9zA9zZgoIIOXpKK4lTQvnsQ8Jw_rPX7NanJM

###

POST http://localhost:4321/api/v1/wallet/operation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzczMzE1MDUsInN1YiI6Ik9iamVjdElEKFwiNjNmMjg3ZjRlYzdkMjc3N2RiYzE3YjRhXCIpIn0.YOb58XlYWZPaxrbOUfkkvCfkd4NSfL_B9dJuAZWD2P0

{
  "walletId": "63f8dd0b7970cbe2303344fe",
  "income": false,
  "description": "some test operation #5",
  "sum": "-50"
}


